Merged branch `master` into `feature-issue77`.
Squashed commit of the following:

commit e5ec7b7837a2d49a0b5aac5547ab9fab699b75d5
Merge: abd77e3 d23381e
Author: Antoine Beauchamp <end2endzone@gmail.com>
Date:   Mon Jan 20 19:49:08 2025 -0500

    Merge pull request #88 from end2endzone/feature-issue87

    Feature issue #87

commit d23381e2da63448b6a6a53969973b5d58732f42b
Author: Antoine Beauchamp <end2endzone@gmail.com>
Date:   Sun Jan 19 17:41:45 2025 -0500

    * Fixed issue #87: TestTiming.testGetMicrosecondsTimerAgaintsSleep() fails on macOS with more than 150ms difference.

commit abd77e3ddeb7a49485f25586a38ea8b13538d811
Merge: 270aba6 da6613d
Author: Antoine Beauchamp <end2endzone@gmail.com>
Date:   Sun Jan 19 17:24:37 2025 -0500

    Merge pull request #86 from end2endzone/feature-issue66

    Feature issue #66

commit da6613d74d596427195f5e56a540f0ffbe4c4702
Author: Antoine Beauchamp <end2endzone@gmail.com>
Date:   Sun Jan 19 17:11:11 2025 -0500

    Fixed compilation error `console.h:85:48: error: ‘size_t’ has not been declared`

commit 270aba63458da6924801fb74d66ac8968f53be1d
Author: Antoine Beauchamp <end2endzone@gmail.com>
Date:   Sun Jan 19 17:03:37 2025 -0500

    Implemented ra::console::PrintHeaderBox() and visual tests.

commit b92254a5b788df433a800602ee5e719e98489961
Author: Antoine Beauchamp <end2endzone@gmail.com>
Date:   Sun Jan 19 16:58:28 2025 -0500

    * Fixed issue #66: Function ra::console::GetDimension() returns size of console window instead of buffer on Windows.

commit 5651aeb2f0bfe020c208e9a6ead40547ad3a0735
Author: Antoine Beauchamp <end2endzone@gmail.com>
Date:   Sun Jan 19 16:57:42 2025 -0500

    Implemented GetWindowDimension() and GetBufferDimension() with tests.
    Fixed GetDimension() wrong meaning.

commit 735d714a8fba3af065fd6b9ee0cd0e22fa9ef335
Merge: fee1355 a08f77e
Author: Antoine Beauchamp <end2endzone@gmail.com>
Date:   Sun Jan 19 13:35:36 2025 -0500

    Merge pull request #85 from end2endzone/feature-issue83

    Feature issue #83

commit a08f77ecb16056def28bb93d25244cfedb37d8c5
Author: Antoine Beauchamp <end2endzone@gmail.com>
Date:   Sun Jan 19 12:54:14 2025 -0500

    Redesigned test `TestTiming.testGetMillisecondsTimerAgaintsSleep()`. See https://github.com/end2endzone/RapidAssist/issues/83#issuecomment-2600960068 for details.

commit e278f9a53fe8e2b589506f12b83e9046d92515e0
Author: Antoine Beauchamp <end2endzone@gmail.com>
Date:   Sun Jan 19 11:10:27 2025 -0500

    * Fixed issue #83: Fail the build when unit tests are failing but run all remaining workflow steps anyway.

commit dca581e7b4c37393519e30b373da53c35e94219a
Author: Antoine Beauchamp <end2endzone@gmail.com>
Date:   Sun Jan 19 11:08:21 2025 -0500

    Revert "Failing tests on purpose for issue #83."

    This reverts commit e6dff536633c0526c28a345f415f8f4d0b817c3f.

commit fce0d1a05ac5483f18aa9aa0e33e0852dd6c1b94
Author: Antoine Beauchamp <end2endzone@gmail.com>
Date:   Sun Jan 19 10:47:50 2025 -0500

    Using an `if` statement in each steps that need to run even if the unit tests have failed. See comment https://github.com/end2endzone/RapidAssist/issues/83#issuecomment-2600915392 for details.

commit 1554596b0b4c3f0d6afe32316535c3b4d9eca6ed
Author: Antoine Beauchamp <end2endzone@gmail.com>
Date:   Sun Jan 19 07:40:46 2025 -0500

    Setup all worlflows to continue on unit test error

commit e6dff536633c0526c28a345f415f8f4d0b817c3f
Author: Antoine Beauchamp <end2endzone@gmail.com>
Date:   Sun Jan 19 07:34:28 2025 -0500

    Failing tests on purpose for issue #83.

commit 2f896cd078c905aaf155d6003f2af1556f3d1e68
Author: Antoine Beauchamp <end2endzone@gmail.com>
Date:   Sun Jan 19 07:26:35 2025 -0500

    Disabled silencing errors when running unit tests in files `test_script.bat` and `test_script.sh`.

commit fee1355c7da0b2c3a96ed914eca6728313b321ce
Merge: 7afd5f0 ca220c2
Author: Antoine Beauchamp <end2endzone@gmail.com>
Date:   Sun Jan 19 07:16:54 2025 -0500

    Merge pull request #84 from end2endzone/feature-issue78

    Feature issue #78

commit ca220c2a187dd6f1d43ed9337abde680fabde878
Author: Antoine Beauchamp <end2endzone@gmail.com>
Date:   Sat Jan 18 21:38:26 2025 -0500

    Fixed a bad test design in TestTiming.testTimestampToStringUtcTime(). An assertion failed and was showing the following error on system whose local time is UTC: `Expected: (ts_now_utc_str) != (ts_now_local_str), actual: "2025-01-19 02:22:46.051097" vs "2025-01-19 02:22:46.051097"`.

commit 97adfed743dafb36779af7cbda88cab074f52da6
Author: Antoine Beauchamp <end2endzone@gmail.com>
Date:   Sat Jan 18 21:19:29 2025 -0500

    Fixed a bad test design. An assertion failed and was showing the following error on system whose local time is UTC: `Expected: (ts_epoch_utc_str) != (ts_epoch_local_str), actual: "1970-01-01 00:00:00.000000" vs "1970-01-01 00:00:00.000000"`.

commit 6364b2b42eb60acf3b5773198b5dbb910735a0a4
Author: Antoine Beauchamp <end2endzone@gmail.com>
Date:   Sat Jan 18 08:51:13 2025 -0500

    Ignore desktop.ini used for setting a directory icon on Windows

commit f2e3b858ffbfacb5a1c52236c13f484d16156d1e
Author: Antoine Beauchamp <end2endzone@gmail.com>
Date:   Sat Jan 18 08:45:22 2025 -0500

    * Fixed issue #78: Get current date and time in microseconds resolution.